---
- name: Configure master node
  hosts: master_server
  become: yes
  tasks:
    
    - name: Update apt-get(yum in centos) repository
      apt:
        update_cache: yes

    - name: Execute the script
      ansible.builtin.script: ./scripts/master-script.sh

- name: Configure worker node 1
  hosts: worker1
  become: yes
  tasks:
    
    - name: Update apt-get(yum in centos) repository
      apt:
        update_cache: yes

    - name: Execute the script
      ansible.builtin.script: ./scripts/worker1-script.sh

- name: Configure worker node 2
  hosts: worker2
  become: yes
  tasks:
    
    - name: Update apt-get(yum in centos) repository
      apt:
        update_cache: yes

    - name: Execute the script
      ansible.builtin.script: ./scripts/worker2-script.sh